helm:
  releaseName: csi-driver-nfs
  repo: oci://registry.lab.internal:5000/charts/csi-driver-nfs
  valuesFiles:
    - csi-driver-nfs-values.yaml
  version: 4.13.4
name: csi-driver-nfs
namespace: kube-system