helm:
  releaseName: nfs-csi-driver
  repo: oci://registry.lab.internal:5000/charts/nfs-csi-driver
  valuesFiles:
    - nfs-csi-driver-values.yaml
  version: 4.13.4
name: nfs-csi-driver
namespace: kube-system