apiVersion: v1
kind: Config
clusters:
- name: "demo-cluster"
  cluster:
    server: "https://rancher.home.internal/k8s/clusters/c-m-p224mghg"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYyekNDQ\
      ThPZ0F3SUJBZ0lVTTA1eHB1KzE1eEZKZ1JsVnN2YTVkVFFaVFVnd0RRWUpLb1pJaHZjTkFRRU4KQ\
      lFBd1JERUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQU1NRGtGamIzTjBZU0JJYjIxbElFTkJNU\
      Th3RFFZRApWUVFIREFaRVlXeHNZWE14Q3pBSkJnTlZCQWdNQWxSWU1CNFhEVEkyTURrd05qRXdNR\
      EExTlZvWERUTTJNRGt3Ck5qRXdNREExTlZvd1JERUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQ\
      U1NRGtGamIzTjBZU0JJYjIxbElFTkIKTVE4d0RRWURWUVFIREFaRVlXeHNZWE14Q3pBSkJnTlZCQ\
      WdNQWxSWU1JSUNJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQWc4QU1JSUNDZ0tDQWdFQXlqUEc5Z\
      WRIM3p3NVR6WlhJS1JPcUxRSEVJR1JvVzliUlZDUWV2SGNjRmU0CjVqOVRyN3JSdWVzc1EvZlFXU\
      Xd6NElUcTR1dmxpZU9SeDhQalBQVlk3S3RhQmF2UHpYb3hnZit2MjRCYktMa2YKSU1LVHRYQkNHe\
      DJmS0NoaVp6TENMUXNvZCtuOHNLRDlhU2lBU1VjKzg4bG1mOCthY0t0TmFmWGdUZ09qL09kWQpiT\
      isrekRwKytrZ0tQSWg1b3ZYME1ya2FjN3pYL2M4T2taRGQvL1lVcjJhZEUwN0gzVXRyK25Bcmw3T\
      ndubmdCCkhnaFpNRW1Pcll4a0d2dWFjcm5vUzZxZ0toN1I3Rk5ZVFRZSTk2RmdYdzFzbDZRYXFLT\
      25pc2ZqS2hYRjJyUXQKa0RZQVJxT09qRit2bjUvN00zTUl3alhEMEtMbUtta3ZsejVCUkdXWDJEQ\
      VFsWDd2L3daaUM2SC9GODVHWHlXOQp4TTJqRUtPUXNIUEhYVEI3eDRXNVFVWGdYam9PMzY5TkJlW\
      WxPMmxvOTB1bVhqemtuVGlPd1RyNDFhWDcwZjBvCjcydEhWOVlSM3Q1YWtGekY1WnRYNHhyMzhub\
      mJlUmN4VmNGWGVwSTlzZzlCVU53cjBpUG1LUzl5V1hia2MyR3EKekZsdmxHUlFEOUZDQVdwbVFvW\
      lQrOURjeUVCbU5LU0pLV0U1Q0NYOXArUDR4cnh5T3V4ZlA5aENMOWNOTjBrWApNSWRiMXc5a1BRM\
      UlEdHJuSmE1TDVWSzhXaHIrbkpuVGJZMWdZMllkK1RVRXZ6aXF5RUhLaFFLVUpiakhPNnFpCjZmM\
      zRxNEdrSk9xS0Y2Skdjb2k0YUYzaEIvN0ZKR3l1enNhOUhVcTVrUHFhYXNGbUxqYkpIR1pYM2dTc\
      FhyRUMKQXdFQUFhT0J4RENCd1RBZEJnTlZIUTRFRmdRVXI4UW12M0dHeXpjRFN0TkdSTkpXZFlOS\
      2tXY3dEd1lEVlIwVApBUUgvQkFVd0F3RUIvekFPQmdOVkhROEJBZjhFQkFNQ0FRWXdmd1lEVlIwa\
      kJIZ3dkb0FVcjhRbXYzR0d5emNEClN0TkdSTkpXZFlOS2tXZWhTS1JHTUVReEN6QUpCZ05WQkFZV\
      EFsVlRNUmN3RlFZRFZRUUREQTVCWTI5emRHRWcKU0c5dFpTQkRRVEVQTUEwR0ExVUVCd3dHUkdGc\
      2JHRnpNUXN3Q1FZRFZRUUlEQUpVV0lJVU0wNXhwdSsxNXhGSgpnUmxWc3ZhNWRUUVpUVWd3RFFZS\
      ktvWklodmNOQVFFTkJRQURnZ0lCQUw2dkhUY2RZVGdIcDNkNHpnb0FLbE9VCmdwR1J1STBNQ2F6N\
      Dd5MnJ5WW9FM3ZMZVFOb29wcFZ6aE5jRjBTbUtvTVBldDh4SndicTJwS0E3Y09PTzRuakoKeERiR\
      HRmd3RaUFp0NC8wTDA1VEJ2YVlKRXN0dkJscEY4eElQRnZIK21sNEZDWjYvNHhtRklJb2lEaUdKN\
      HRBeAowWEloNmM3MU9IVjlmVWlDUUFiaXY3dGYwNHlMTnNXSjU5QldWdHUxRktjN1dqOXRxQkhNR\
      DdPckRlcmRETkVMClcvZ1cwQUU0RWRIWDkwUFhCalZQMXJFTEt3cHpFdjZhU096YU1jR0VwbC96N\
      FBnOXc0MU5vRWtockpsektZNksKN1UzUVJHRTlEK1NvS2hCbnprenFBcGpGVVpZT2ZING8zWC9Jd\
      Uc5ZEwvY0dXbmt2QTNSaEZFUWdsUlR1Wi84KwpaYndTaDNHMFNBR0tGbEFtaXpOb1ZnejlCeUt5N\
      mFmelVXY3pmdUJJQ2x6b3EzcWgrYVhpclRBcmdIOENHN1NKCkF0RjBWNHFZTzlEUkltVW9teHY0Y\
      k5HVTZiQ0ZaYTNXaVgzVXlpMUx5SjJ2bDUxbG1CL1I5V3pNWjBjMmZ0RDcKSDVoSTU0NFErdExRd\
      mUvUElXZllNcEovSkVkTnE3ZzROTWlXZ3VBR0hRMGdEMmM5c0NTZzFWM1IzVHl5c09sMwpHbkpxc\
      0xrMk9Ibk83UjN0QlhNNHJtT3g0UlhFSXhEY0EwV2FNQ29TOE0rWGhYdU9hTUNTeUI0WGlWWi9Hd\
      jVtCjF2ald5VTk2SXp3VysyZ2g2L3hMcHJSaU9Bd2xhYlE0eVo3bUZGTDRrNC9CQ0h6VXBKanlhQ\
      0NXQXJWOTdHdDAKMnhpUWpIS1lBNkxZWnlmb3BMa2cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tL\
      Q=="

users:
- name: "demo-cluster"
  user:
    token: "kubeconfig-user-q6tm6z7jzk:rzhkmr69krgkrv7g9l6n9wdc2dr27h5bl4sp5cwslddnqqg2pwchp6"


contexts:
- name: "demo-cluster"
  context:
    user: "demo-cluster"
    cluster: "demo-cluster"

current-context: "demo-cluster"
